// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​l​e​c​t​ ​L​a​n​g​u​a​g​e
	 */
	selectLanguage: string
	welcome: {
		/**
		 * B​i​t​c​o​i​n​ ​i​s​ ​f​o​r​ ​a​l​l​ ​o​f​ ​u​s
		 */
		subtitle: string
		/**
		 * C​r​e​a​t​e​ ​n​e​w​ ​w​a​l​l​e​t
		 */
		createNewWallet: string
		/**
		 * R​e​s​t​o​r​e​ ​w​a​l​l​e​t
		 */
		restoreWallet: string
		/**
		 * I​ ​a​l​r​e​a​d​y​ ​h​a​v​e​ ​a​ ​w​a​l​l​e​t
		 */
		iAlreadyHaveAWallet: string
		/**
		 *  ​Y​o​u​r​ ​w​a​l​l​e​t​,​ ​y​o​u​r​ ​c​o​i​n​s​.​ ​
	​ ​1​0​0​%​ ​o​p​e​n​-​s​o​u​r​c​e​ ​&​ ​o​p​e​n​-​d​e​s​i​g​n​.​ ​
	​ ​B​u​i​l​t​ ​w​i​t​h​ ​❤​️​ ​i​n​ ​U​g​a​n​d​a
		 */
		footer: string
	}
	onboardingSlides: {
		slide1: {
			/**
			 * M​a​n​a​g​e​ ​y​o​u​r​ ​b​i​t​c​o​i​n
			 */
			title: string
			/**
			 * H​a​v​e​ ​f​u​l​l​ ​c​o​n​t​r​o​l​ ​w​i​t​h​ ​t​h​i​s​ ​s​e​l​f​-​c​u​s​t​o​d​y​ ​w​a​l​l​e​t​.​ ​N​o​ ​o​n​e​ ​e​l​s​e​ ​c​a​n​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​b​i​t​c​o​i​n​.
			 */
			text: string
		}
		slide2: {
			/**
			 * C​o​n​v​e​n​i​e​n​t​ ​b​a​c​k​u​p​s​ ​w​i​t​h​ ​c​l​o​u​d​ ​&​ ​m​a​n​u​a​l​ ​s​t​o​r​a​g​e
			 */
			title: string
			/**
			 * Y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e​ ​w​i​l​l​ ​b​e​ ​e​n​c​r​y​p​t​e​d​ ​a​n​d​ ​b​a​c​k​e​d​ ​u​p​ ​t​o​ ​y​o​u​r​ ​c​l​o​u​d​ ​p​r​o​v​i​d​e​r​,​ ​o​n​l​y​ ​y​o​u​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​a​c​c​e​s​s​ ​i​t​.
			 */
			text: string
		}
		slide3: {
			/**
			 * K​e​e​p​ ​y​o​u​r​ ​w​a​l​l​e​t​ ​a​n​d​ ​b​i​t​c​o​i​n​ ​s​e​c​u​r​e
			 */
			title: string
			/**
			 * E​n​a​b​l​e​ ​f​a​c​e​ ​d​e​t​e​c​t​i​o​n​ ​o​r​ ​s​e​t​ ​a​ ​p​i​n​ ​f​o​r​ ​e​x​t​r​a​ ​s​e​c​u​r​i​t​y​.
			 */
			text: string
		}
		labels: {
			/**
			 * G​e​t​ ​s​t​a​r​t​e​d
			 */
			done: string
			/**
			 * B​a​c​k
			 */
			previous: string
			/**
			 * N​e​x​t
			 */
			next: string
		}
	}
	pinCode: {
		/**
		 * C​r​e​a​t​e​ ​a​ ​P​I​N
		 */
		create: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​P​I​N
		 */
		createNew: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​P​I​N​ ​a​g​a​i​n​ ​t​o​ ​c​o​n​f​i​r​m
		 */
		verify: string
		/**
		 * C​h​a​n​g​e​ ​P​I​N
		 */
		changePIN: string
		/**
		 * T​h​e​ ​P​I​N​s​ ​d​i​d​n​'​t​ ​m​a​t​c​h
		 */
		pinsDontMatch: string
		/**
		 * P​l​e​a​s​e​ ​u​s​e​ ​a​ ​s​t​r​o​n​g​e​r​ ​P​I​N
		 */
		invalidPin: string
		/**
		 * C​h​o​o​s​e​ ​a​ ​6​ ​d​i​g​i​t​ ​P​I​N​ ​y​o​u​’​l​l​ ​r​e​m​e​m​b​e​r
		 */
		guideTitle: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​P​I​N​ ​a​g​a​i​n​ ​t​o​ ​c​o​n​f​i​r​m​.
		 */
		guideConfirm: string
		/**
		 * Y​o​u​r​ ​P​I​N​ ​i​s​ ​h​o​w​ ​y​o​u​’​l​l​ ​s​e​c​u​r​e​ ​y​o​u​r​ ​w​a​l​l​e​t​.
		 */
		pinCodeGuide: string
		/**
		 * S​e​l​e​c​t​ ​P​I​N
		 */
		selectPIN: string
	}
	recoveryPhraseIntro: {
		/**
		 * L​e​t​'​s​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e
		 */
		title: string
		/**
		 * P​a​y​ ​a​t​t​e​n​t​i​o​n​,​ ​t​h​i​s​ ​i​s​ ​i​m​p​o​r​t​a​n​t​!
		 */
		subtitle: string
		/**
		 * A​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e​ ​i​s​ ​a​ ​g​r​o​u​p​ ​o​f​ ​1​2​ ​r​a​n​d​o​m​ ​w​o​r​d​s​.
		 */
		fact1: string
		/**
		 * I​t​ ​i​s​ ​t​h​e​ ​o​n​l​y​ ​w​a​y​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​w​a​l​l​e​t​ ​i​f​ ​y​o​u​r​ ​p​h​o​n​e​ ​i​s​ ​l​o​s​t​ ​o​r​ ​s​t​o​l​e​n​.
		 */
		fact2: string
		/**
		 * N​e​v​e​r​ ​s​h​a​r​e​ ​y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e​ ​w​i​t​h​ ​a​n​y​o​n​e​.​ ​A​n​y​o​n​e​ ​w​h​o​ ​h​a​s​ ​i​t​ ​c​a​n​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​f​u​n​d​s​.
		 */
		fact3: string
		/**
		 * W​r​i​t​e​ ​t​h​e​s​e​ ​w​o​r​d​s​ ​d​o​w​n​ ​i​n​ ​o​r​d​e​r​ ​o​n​ ​a​ ​p​i​e​c​e​ ​o​f​ ​p​a​p​e​r​ ​a​n​d​ ​s​t​o​r​e​ ​i​t​ ​s​o​m​e​w​h​e​r​e​ ​s​a​f​e​ ​t​h​a​t​ ​y​o​u​ ​w​i​l​l​ ​r​e​m​e​m​b​e​r​.
		 */
		fact4: string
		/**
		 * C​o​n​t​i​n​u​e
		 */
		ctaBtn: string
	}
	manualBackup: {
		/**
		 * Y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e
		 */
		inputHeader: string
		/**
		 * S​e​e​d​ ​o​r​ ​R​e​c​o​v​e​r​y​ ​P​h​r​a​s​e​ ​h​e​r​e
		 */
		inputPlaceholder: string
		/**
		 * W​r​i​t​e​ ​i​t​ ​d​o​w​n​ ​s​o​m​e​ ​p​l​a​c​e​ ​s​a​f​e​.​ ​W​e​ ​w​i​l​l​ ​v​e​r​i​f​y​ ​t​h​i​s​ ​o​n​ ​t​h​e​ ​n​e​x​t​ ​p​a​g​e​.​ ​Y​o​u​ ​m​i​g​h​t​ ​b​e​ ​t​e​m​p​t​e​d​ ​t​o​,​ ​b​u​t​ ​d​o​ ​n​o​t​ ​s​a​v​e​ ​t​h​i​s​ ​o​n​ ​y​o​u​r​ ​p​h​o​n​e​!
		 */
		warning: string
		/**
		 * Y​e​s​,​ ​I​ ​h​a​v​e​ ​w​r​i​t​t​e​n​ ​d​o​w​n​ ​m​y​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e
		 */
		writtenConfirmation: string
		/**
		 * L​e​a​r​n​ ​m​o​r​e
		 */
		topLearnMoreBtn: string
		/**
		 * B​a​c​k​ ​u​p​ ​o​n​ ​i​C​l​o​u​d
		 */
		icloudBackupBtn: string
		/**
		 * B​a​c​k​ ​u​p​ ​o​n​ ​G​o​o​g​l​e​ ​D​r​i​v​e
		 */
		gdriveBackupBtn: string
		/**
		 * B​a​c​k​ ​u​p​ ​m​a​n​u​a​l​l​y
		 */
		manualBackupBtn: string
	}
	manualBackupQuiz: {
		/**
		 * C​o​n​f​i​r​m​ ​M​a​n​u​a​l​ ​B​a​c​k​u​p
		 */
		headerTitle: string
		cancelDialog: {
			/**
			 * Y​o​u​ ​s​h​o​u​l​d​ ​f​i​n​i​s​h
			 */
			title: string
			/**
			 * Y​o​u​r​ ​R​e​c​o​v​e​r​y​ ​P​h​r​a​s​e​ ​i​s​ ​e​x​t​r​e​m​e​l​y​ ​i​m​p​o​r​t​a​n​t​.​ ​W​i​t​h​o​u​t​ ​t​h​i​s​ ​b​a​c​k​u​p​,​ ​y​o​u​ ​w​i​l​l​ ​l​o​s​e​ ​a​l​l​ ​y​o​u​r​ ​b​i​t​c​o​i​n​ ​f​o​r​e​v​e​r​.
			 */
			body: string
			/**
			 * C​o​m​p​l​e​t​e​ ​N​o​w
			 */
			action: string
			/**
			 * F​i​n​i​s​h​ ​L​a​t​e​r
			 */
			secondary: string
		}
		/**
		 * S​e​l​e​c​t​ ​t​h​e​ ​<​0​>​{​{​o​r​d​i​n​a​l​}​}​<​/​0​>​ ​w​o​r​d​ ​o​f​ ​y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e​?
		 */
		backupQuizWordCount: string
		ordinals: {
			/**
			 * z​e​r​o​t​h
			 */
			'0': string
			/**
			 * f​i​r​s​t
			 */
			'1': string
			/**
			 * s​e​c​o​n​d
			 */
			'2': string
			/**
			 * t​h​i​r​d
			 */
			'3': string
			/**
			 * f​o​u​r​t​h
			 */
			'4': string
			/**
			 * f​i​f​t​h
			 */
			'5': string
			/**
			 * s​i​x​t​h
			 */
			'6': string
			/**
			 * s​e​v​e​n​t​h
			 */
			'7': string
			/**
			 * e​i​g​h​t​h
			 */
			'8': string
			/**
			 * n​i​n​t​h
			 */
			'9': string
			/**
			 * t​e​n​t​h
			 */
			'10': string
			/**
			 * e​l​e​v​e​n​t​h
			 */
			'11': string
			/**
			 * t​w​e​l​f​t​h
			 */
			'12': string
		}
		/**
		 * V​e​r​i​f​y
		 */
		verifyBtn: string
		/**
		 * T​h​e​ ​R​e​c​o​v​e​r​y​ ​P​h​r​a​s​e​ ​y​o​u​ ​e​n​t​e​r​e​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t​.​ ​T​r​y​ ​a​g​a​i​n​.
		 */
		failed: string
		/**
		 * S​t​a​r​t​ ​o​v​e​r
		 */
		resetBtn: string
		backupVerified: {
			/**
			 * B​a​c​k​ ​U​p​ ​V​e​r​i​f​i​e​d
			 */
			title: string
			/**
			 * W​e​l​l​ ​d​o​n​e​!​.​ ​
		​ ​P​l​e​a​s​e​ ​k​e​e​p​ ​y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​p​h​r​a​s​e​ ​s​a​f​e​.​ ​M​e​m​o​r​i​z​e​ ​i​t​ ​i​f​ ​y​o​u​ ​c​a​n​.
			 */
			text: string
		}
	}
	protectWallet: {
		/**
		 * P​r​o​t​e​c​t​ ​y​o​u​r​ ​w​a​l​l​e​t
		 */
		title: string
		/**
		 * A​d​d​ ​a​n​ ​e​x​t​r​a​ ​l​a​y​e​r​ ​o​f​ ​s​e​c​u​r​i​t​y​ ​t​o​ ​p​r​e​v​e​n​t​ ​a​n​y​o​n​e​ ​f​r​o​m​ ​a​c​c​e​s​s​i​n​g​ ​y​o​u​r​ ​w​a​l​l​e​t​ ​a​n​d​ ​b​i​t​c​o​i​n
		 */
		subtitle: string
		/**
		 * U​s​e​ ​{​{​b​i​o​m​e​t​r​y​T​y​p​e​}​}
		 */
		useBiometricsBtn: string
		/**
		 * C​r​e​a​t​e​ ​P​I​N
		 */
		createPinBtn: string
		biometryType: {
			/**
			 * F​a​c​e​ ​I​D
			 */
			FaceID: string
			/**
			 * T​o​u​c​h​ ​I​D
			 */
			TouchID: string
			/**
			 * F​i​n​g​e​r​p​r​i​n​t​ ​r​e​c​o​g​n​i​t​i​o​n
			 */
			Fingerprint: string
		}
	}
	sendBitcoin: {
		/**
		 * N​e​x​t
		 */
		nextBtn: string
		confirmation: {
			/**
			 * C​o​n​f​i​r​m​ ​t​r​a​n​s​a​c​t​i​o​n
			 */
			headerTitle: string
			/**
			 * S​e​n​d​ ​B​i​t​c​o​i​n
			 */
			title: string
			/**
			 * A​m​o​u​n​t​ ​i​n​ ​B​T​C
			 */
			amountLabel: string
			/**
			 * A​m​o​u​n​t​ ​i​n​ ​{​{​l​o​c​a​l​C​u​r​r​e​n​c​y​}​}
			 */
			localAmountLabel: string
			/**
			 * A​d​d​ ​n​o​t​e​ ​t​o​ ​s​e​l​f
			 */
			addNote: string
			/**
			 * F​e​e​s
			 */
			fees: string
			/**
			 * S​e​n​d​ ​B​i​t​c​o​i​n
			 */
			sendBtn: string
		}
	}
	walletHome: {
		/**
		 * T​o​t​a​l​ ​b​a​l​a​n​c​e
		 */
		totalBalanceHeader: string
		/**
		 * R​e​c​e​n​t​ ​A​c​t​i​v​i​t​y
		 */
		recentActivityHeader: string
	}
	/**
	 * A​d​d​ ​n​o​t​e​ ​t​o​ ​s​e​l​f
	 */
	addNote: string
	/**
	 * S​e​l​e​c​t​ ​F​e​e​s
	 */
	selectFees: string
	biometrics: {
		/**
		 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y
		 */
		confirmIdentity: string
		/**
		 * S​t​o​r​a​g​e
		 */
		encryptStorage: string
		/**
		 * A​l​l​ ​y​o​u​r​ ​w​a​l​l​e​t​s​ ​w​i​l​l​ ​b​e​ ​r​e​m​o​v​e​d​ ​a​n​d​ ​y​o​u​r​ ​s​t​o​r​a​g​e​ ​w​i​l​l​ ​b​e​ ​d​e​c​r​y​p​t​e​d​.​ ​A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​r​o​c​e​e​d​?
		 */
		removeDecrypt: string
		/**
		 * Y​o​u​r​ ​d​e​v​i​c​e​ ​d​o​e​s​ ​n​o​t​ ​h​a​v​e​ ​a​ ​p​a​s​s​c​o​d​e​.​ ​I​n​ ​o​r​d​e​r​ ​t​o​ ​p​r​o​c​e​e​d​,​ ​p​l​e​a​s​e​ ​c​o​n​f​i​g​u​r​e​ ​a​ ​p​a​s​s​c​o​d​e​ ​i​n​ ​t​h​e​ ​S​e​t​t​i​n​g​s​ ​a​p​p​.
		 */
		noPasscode: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​a​t​t​e​m​p​t​e​d​ ​t​o​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​1​0​ ​t​i​m​e​s​.​ ​W​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​s​t​o​r​a​g​e​?​ ​T​h​i​s​ ​w​i​l​l​ ​r​e​m​o​v​e​ ​a​l​l​ ​w​a​l​l​e​t​s​ ​a​n​d​ ​d​e​c​r​y​p​t​ ​y​o​u​r​ ​s​t​o​r​a​g​e​.
		 */
		triedTenTimes: string
	}
	alerts: {
		/**
		 * A​l​e​r​t
		 */
		'default': string
	}
}

export type TranslationFunctions = {
	/**
	 * Select Language
	 */
	selectLanguage: () => LocalizedString
	welcome: {
		/**
		 * Bitcoin is for all of us
		 */
		subtitle: () => LocalizedString
		/**
		 * Create new wallet
		 */
		createNewWallet: () => LocalizedString
		/**
		 * Restore wallet
		 */
		restoreWallet: () => LocalizedString
		/**
		 * I already have a wallet
		 */
		iAlreadyHaveAWallet: () => LocalizedString
		/**
		 *  Your wallet, your coins. 
	 100% open-source & open-design. 
	 Built with ❤️ in Uganda
		 */
		footer: () => LocalizedString
	}
	onboardingSlides: {
		slide1: {
			/**
			 * Manage your bitcoin
			 */
			title: () => LocalizedString
			/**
			 * Have full control with this self-custody wallet. No one else can access your bitcoin.
			 */
			text: () => LocalizedString
		}
		slide2: {
			/**
			 * Convenient backups with cloud & manual storage
			 */
			title: () => LocalizedString
			/**
			 * Your recovery phrase will be encrypted and backed up to your cloud provider, only you will be able to access it.
			 */
			text: () => LocalizedString
		}
		slide3: {
			/**
			 * Keep your wallet and bitcoin secure
			 */
			title: () => LocalizedString
			/**
			 * Enable face detection or set a pin for extra security.
			 */
			text: () => LocalizedString
		}
		labels: {
			/**
			 * Get started
			 */
			done: () => LocalizedString
			/**
			 * Back
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
	}
	pinCode: {
		/**
		 * Create a PIN
		 */
		create: () => LocalizedString
		/**
		 * Create a new PIN
		 */
		createNew: () => LocalizedString
		/**
		 * Enter your PIN again to confirm
		 */
		verify: () => LocalizedString
		/**
		 * Change PIN
		 */
		changePIN: () => LocalizedString
		/**
		 * The PINs didn't match
		 */
		pinsDontMatch: () => LocalizedString
		/**
		 * Please use a stronger PIN
		 */
		invalidPin: () => LocalizedString
		/**
		 * Choose a 6 digit PIN you’ll remember
		 */
		guideTitle: () => LocalizedString
		/**
		 * Enter your PIN again to confirm.
		 */
		guideConfirm: () => LocalizedString
		/**
		 * Your PIN is how you’ll secure your wallet.
		 */
		pinCodeGuide: () => LocalizedString
		/**
		 * Select PIN
		 */
		selectPIN: () => LocalizedString
	}
	recoveryPhraseIntro: {
		/**
		 * Let's create your recovery phrase
		 */
		title: () => LocalizedString
		/**
		 * Pay attention, this is important!
		 */
		subtitle: () => LocalizedString
		/**
		 * A recovery phrase is a group of 12 random words.
		 */
		fact1: () => LocalizedString
		/**
		 * It is the only way to access your wallet if your phone is lost or stolen.
		 */
		fact2: () => LocalizedString
		/**
		 * Never share your recovery phrase with anyone. Anyone who has it can access your funds.
		 */
		fact3: () => LocalizedString
		/**
		 * Write these words down in order on a piece of paper and store it somewhere safe that you will remember.
		 */
		fact4: () => LocalizedString
		/**
		 * Continue
		 */
		ctaBtn: () => LocalizedString
	}
	manualBackup: {
		/**
		 * Your recovery phrase
		 */
		inputHeader: () => LocalizedString
		/**
		 * Seed or Recovery Phrase here
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Write it down some place safe. We will verify this on the next page. You might be tempted to, but do not save this on your phone!
		 */
		warning: () => LocalizedString
		/**
		 * Yes, I have written down my recovery phrase
		 */
		writtenConfirmation: () => LocalizedString
		/**
		 * Learn more
		 */
		topLearnMoreBtn: () => LocalizedString
		/**
		 * Back up on iCloud
		 */
		icloudBackupBtn: () => LocalizedString
		/**
		 * Back up on Google Drive
		 */
		gdriveBackupBtn: () => LocalizedString
		/**
		 * Back up manually
		 */
		manualBackupBtn: () => LocalizedString
	}
	manualBackupQuiz: {
		/**
		 * Confirm Manual Backup
		 */
		headerTitle: () => LocalizedString
		cancelDialog: {
			/**
			 * You should finish
			 */
			title: () => LocalizedString
			/**
			 * Your Recovery Phrase is extremely important. Without this backup, you will lose all your bitcoin forever.
			 */
			body: () => LocalizedString
			/**
			 * Complete Now
			 */
			action: () => LocalizedString
			/**
			 * Finish Later
			 */
			secondary: () => LocalizedString
		}
		/**
		 * Select the <0>{{ordinal}}</0> word of your recovery phrase?
		 */
		backupQuizWordCount: (arg0: number | string | boolean) => LocalizedString
		ordinals: {
			/**
			 * zeroth
			 */
			'0': () => LocalizedString
			/**
			 * first
			 */
			'1': () => LocalizedString
			/**
			 * second
			 */
			'2': () => LocalizedString
			/**
			 * third
			 */
			'3': () => LocalizedString
			/**
			 * fourth
			 */
			'4': () => LocalizedString
			/**
			 * fifth
			 */
			'5': () => LocalizedString
			/**
			 * sixth
			 */
			'6': () => LocalizedString
			/**
			 * seventh
			 */
			'7': () => LocalizedString
			/**
			 * eighth
			 */
			'8': () => LocalizedString
			/**
			 * ninth
			 */
			'9': () => LocalizedString
			/**
			 * tenth
			 */
			'10': () => LocalizedString
			/**
			 * eleventh
			 */
			'11': () => LocalizedString
			/**
			 * twelfth
			 */
			'12': () => LocalizedString
		}
		/**
		 * Verify
		 */
		verifyBtn: () => LocalizedString
		/**
		 * The Recovery Phrase you entered is incorrect. Try again.
		 */
		failed: () => LocalizedString
		/**
		 * Start over
		 */
		resetBtn: () => LocalizedString
		backupVerified: {
			/**
			 * Back Up Verified
			 */
			title: () => LocalizedString
			/**
			 * Well done!. 
		 Please keep your recovery phrase safe. Memorize it if you can.
			 */
			text: () => LocalizedString
		}
	}
	protectWallet: {
		/**
		 * Protect your wallet
		 */
		title: () => LocalizedString
		/**
		 * Add an extra layer of security to prevent anyone from accessing your wallet and bitcoin
		 */
		subtitle: () => LocalizedString
		/**
		 * Use {{biometryType}}
		 */
		useBiometricsBtn: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Create PIN
		 */
		createPinBtn: () => LocalizedString
		biometryType: {
			/**
			 * Face ID
			 */
			FaceID: () => LocalizedString
			/**
			 * Touch ID
			 */
			TouchID: () => LocalizedString
			/**
			 * Fingerprint recognition
			 */
			Fingerprint: () => LocalizedString
		}
	}
	sendBitcoin: {
		/**
		 * Next
		 */
		nextBtn: () => LocalizedString
		confirmation: {
			/**
			 * Confirm transaction
			 */
			headerTitle: () => LocalizedString
			/**
			 * Send Bitcoin
			 */
			title: () => LocalizedString
			/**
			 * Amount in BTC
			 */
			amountLabel: () => LocalizedString
			/**
			 * Amount in {{localCurrency}}
			 */
			localAmountLabel: (arg0: number | string | boolean) => LocalizedString
			/**
			 * Add note to self
			 */
			addNote: () => LocalizedString
			/**
			 * Fees
			 */
			fees: () => LocalizedString
			/**
			 * Send Bitcoin
			 */
			sendBtn: () => LocalizedString
		}
	}
	walletHome: {
		/**
		 * Total balance
		 */
		totalBalanceHeader: () => LocalizedString
		/**
		 * Recent Activity
		 */
		recentActivityHeader: () => LocalizedString
	}
	/**
	 * Add note to self
	 */
	addNote: () => LocalizedString
	/**
	 * Select Fees
	 */
	selectFees: () => LocalizedString
	biometrics: {
		/**
		 * Please confirm your identity
		 */
		confirmIdentity: () => LocalizedString
		/**
		 * Storage
		 */
		encryptStorage: () => LocalizedString
		/**
		 * All your wallets will be removed and your storage will be decrypted. Are you sure you want to proceed?
		 */
		removeDecrypt: () => LocalizedString
		/**
		 * Your device does not have a passcode. In order to proceed, please configure a passcode in the Settings app.
		 */
		noPasscode: () => LocalizedString
		/**
		 * You have attempted to enter your password 10 times. Would you like to reset your storage? This will remove all wallets and decrypt your storage.
		 */
		triedTenTimes: () => LocalizedString
	}
	alerts: {
		/**
		 * Alert
		 */
		'default': () => LocalizedString
	}
}

export type Formatters = {}
