export enum Screens {
  ErrorScreen = 'ErrorScreen',
  LangugageChooserScreen = 'LangugageChooserScreen',
  LanguageModal = 'LanguageModal',
  Disclaimer = 'Disclaimer',
  SetPinScreen = 'SetPinScreen',
  EnterPinScreen = 'EnterPinScreen',
  EnableBiometryScreen = 'EnableBiometryScreen',
  WelcomeScreen = 'WelcomeScreen',
  RestoreWalletScreen = 'RestoreWalletScreen',
  WalletHomeScreen = 'WalletHomeScreen',
  OnboardingSlidesScreen = 'OnboardingSlidesScreen',
  Main = 'Main',
  AnimatedModal = 'AnimatedModal',
  DrawerNavigator = 'DrawerNavigator',
  ManualBackupScreen = 'ManualBackupScreen',
  ManualBackupQuizScreen = 'ManualBackupQuizScreen',
  SeedPhraseScreen = 'SeedPhraseScreen',
  SettingsScreen = 'SettingsScreen',
  HelpScreen = 'HelpScreen',
  FAQScreen = 'FAQScreen',
}
