export enum Screens {
  ErrorScreen = 'ErrorScreen',
  InitScreen = 'InitScreen',
  LangugageChooserScreen = 'LangugageChooserScreen',
  LanguageModal = 'LanguageModal',
  Disclaimer = 'Disclaimer',
  SetPinScreen = 'SetPinScreen',
  EnterPinScreen = 'EnterPinScreen',
  EnableBiometryScreen = 'EnableBiometryScreen',
  WelcomeScreen = 'WelcomeScreen',
  RestoreWalletScreen = 'RestoreWalletScreen',
  WalletHomeScreen = 'WalletHomeScreen',
  OnboardingSlidesScreen = 'OnboardingSlidesScreen',
  Main = 'Main',
  AnimatedModal = 'AnimatedModal',
  DrawerNavigator = 'DrawerNavigator',
  ManualBackupScreen = 'ManualBackupScreen',
  ManualBackupQuizScreen = 'ManualBackupQuizScreen',
  SettingsScreen = 'SettingsScreen',
  HelpScreen = 'HelpScreen',
  FAQScreen = 'FAQScreen',
  TestScreen = 'TestScreen',
  StartLN = 'StartLN',
  ReceiveScreen = 'ReceiveScreen',
  LightningChannelsIntroScreen = 'LightningChannelsIntroScreen',
  JITLiquidityScreen = 'JITLiquidityScreen',
  ChannelsScreen = 'ChannelsScreen',
}
